In [41]:
import pandas as pd
import numpy as np
import h5py
import glob
import matplotlib.pyplot as plt
%matplotlib inline

In [143]:
path_single = r"C:\Users\iamte\Downloads\TrainData\img\image_10.h5"
path_single_mask = r'C:\Users\iamte\Downloads\TrainData\mask\mask_1.h5'
TRAIN_PATH = r"C:\Users\iamte\Downloads\TrainData\img\*.h5"
TRAIN_MASK = r'C:\Users\iamte\Downloads\TrainData\mask\*.h5'

In [158]:
TRAIN_XX = np.zeros((3799, 128, 128, 3))
TRAIN_YY = np.zeros((3799, 128, 128))
all_train = glob.glob(TRAIN_PATH)
all_mask = glob.glob(TRAIN_MASK)

for i, (img, mask) in enumerate(zip(all_train, all_mask)):
    print(i, img, mask)
    with h5py.File(path_single) as hdf:
        ls = list(hdf.keys())
        data = np.array(hdf.get('img'))

        data_red = data[:, :, 3]
        data_nir = data[:, :, 7]
        data_ndvi = np.divide(data_nir - data_red,np.add(data_nir, data_red))
        TRAIN_XX[i, :, :, 0] = data_ndvi
        TRAIN_XX[i, :, :, 1] = data[:, :, 12]
        TRAIN_XX[i, :, :, 2] = data[:, :, 13]
    
    
    with h5py.File(path_single_mask) as hdf:
        ls = list(hdf.keys())
        data=np.array(hdf.get('mask'))
        TRAIN_YY[i, :, :] = data
    

0 C:\Users\iamte\Downloads\TrainData\img\image_1.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1.h5
1 C:\Users\iamte\Downloads\TrainData\img\image_10.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_10.h5
2 C:\Users\iamte\Downloads\TrainData\img\image_100.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_100.h5
3 C:\Users\iamte\Downloads\TrainData\img\image_1000.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1000.h5
4 C:\Users\iamte\Downloads\TrainData\img\image_1001.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1001.h5
5 C:\Users\iamte\Downloads\TrainData\img\image_1002.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1002.h5
6 C:\Users\iamte\Downloads\TrainData\img\image_1003.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1003.h5
7 C:\Users\iamte\Downloads\TrainData\img\image_1004.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1004.h5
8 C:\Users\iamte\Downloads\TrainData\img\image_1005.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1005.h5
9 C:\Users\iamte\Downloads\TrainData\img

93 C:\Users\iamte\Downloads\TrainData\img\image_1082.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1082.h5
94 C:\Users\iamte\Downloads\TrainData\img\image_1083.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1083.h5
95 C:\Users\iamte\Downloads\TrainData\img\image_1084.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1084.h5
96 C:\Users\iamte\Downloads\TrainData\img\image_1085.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1085.h5
97 C:\Users\iamte\Downloads\TrainData\img\image_1086.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1086.h5
98 C:\Users\iamte\Downloads\TrainData\img\image_1087.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1087.h5
99 C:\Users\iamte\Downloads\TrainData\img\image_1088.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1088.h5
100 C:\Users\iamte\Downloads\TrainData\img\image_1089.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1089.h5
101 C:\Users\iamte\Downloads\TrainData\img\image_109.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_109.h5
102 C:\Users\iamte\

190 C:\Users\iamte\Downloads\TrainData\img\image_117.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_117.h5
191 C:\Users\iamte\Downloads\TrainData\img\image_1170.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1170.h5
192 C:\Users\iamte\Downloads\TrainData\img\image_1171.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1171.h5
193 C:\Users\iamte\Downloads\TrainData\img\image_1172.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1172.h5
194 C:\Users\iamte\Downloads\TrainData\img\image_1173.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1173.h5
195 C:\Users\iamte\Downloads\TrainData\img\image_1174.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1174.h5
196 C:\Users\iamte\Downloads\TrainData\img\image_1175.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1175.h5
197 C:\Users\iamte\Downloads\TrainData\img\image_1176.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1176.h5
198 C:\Users\iamte\Downloads\TrainData\img\image_1177.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1177.h5
199 C:\Users

284 C:\Users\iamte\Downloads\TrainData\img\image_1254.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1254.h5
285 C:\Users\iamte\Downloads\TrainData\img\image_1255.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1255.h5
286 C:\Users\iamte\Downloads\TrainData\img\image_1256.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1256.h5
287 C:\Users\iamte\Downloads\TrainData\img\image_1257.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1257.h5
288 C:\Users\iamte\Downloads\TrainData\img\image_1258.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1258.h5
289 C:\Users\iamte\Downloads\TrainData\img\image_1259.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1259.h5
290 C:\Users\iamte\Downloads\TrainData\img\image_126.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_126.h5
291 C:\Users\iamte\Downloads\TrainData\img\image_1260.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1260.h5
292 C:\Users\iamte\Downloads\TrainData\img\image_1261.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1261.h5
293 C:\Users

378 C:\Users\iamte\Downloads\TrainData\img\image_1339.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1339.h5
379 C:\Users\iamte\Downloads\TrainData\img\image_134.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_134.h5
380 C:\Users\iamte\Downloads\TrainData\img\image_1340.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1340.h5
381 C:\Users\iamte\Downloads\TrainData\img\image_1341.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1341.h5
382 C:\Users\iamte\Downloads\TrainData\img\image_1342.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1342.h5
383 C:\Users\iamte\Downloads\TrainData\img\image_1343.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1343.h5
384 C:\Users\iamte\Downloads\TrainData\img\image_1344.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1344.h5
385 C:\Users\iamte\Downloads\TrainData\img\image_1345.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1345.h5
386 C:\Users\iamte\Downloads\TrainData\img\image_1346.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1346.h5
387 C:\Users

472 C:\Users\iamte\Downloads\TrainData\img\image_1423.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1423.h5
473 C:\Users\iamte\Downloads\TrainData\img\image_1424.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1424.h5
474 C:\Users\iamte\Downloads\TrainData\img\image_1425.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1425.h5
475 C:\Users\iamte\Downloads\TrainData\img\image_1426.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1426.h5
476 C:\Users\iamte\Downloads\TrainData\img\image_1427.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1427.h5
477 C:\Users\iamte\Downloads\TrainData\img\image_1428.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1428.h5
478 C:\Users\iamte\Downloads\TrainData\img\image_1429.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1429.h5
479 C:\Users\iamte\Downloads\TrainData\img\image_143.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_143.h5
480 C:\Users\iamte\Downloads\TrainData\img\image_1430.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1430.h5
481 C:\Users

565 C:\Users\iamte\Downloads\TrainData\img\image_1507.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1507.h5
566 C:\Users\iamte\Downloads\TrainData\img\image_1508.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1508.h5
567 C:\Users\iamte\Downloads\TrainData\img\image_1509.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1509.h5
568 C:\Users\iamte\Downloads\TrainData\img\image_151.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_151.h5
569 C:\Users\iamte\Downloads\TrainData\img\image_1510.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1510.h5
570 C:\Users\iamte\Downloads\TrainData\img\image_1511.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1511.h5
571 C:\Users\iamte\Downloads\TrainData\img\image_1512.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1512.h5
572 C:\Users\iamte\Downloads\TrainData\img\image_1513.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1513.h5
573 C:\Users\iamte\Downloads\TrainData\img\image_1514.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1514.h5
574 C:\Users

658 C:\Users\iamte\Downloads\TrainData\img\image_1591.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1591.h5
659 C:\Users\iamte\Downloads\TrainData\img\image_1592.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1592.h5
660 C:\Users\iamte\Downloads\TrainData\img\image_1593.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1593.h5
661 C:\Users\iamte\Downloads\TrainData\img\image_1594.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1594.h5
662 C:\Users\iamte\Downloads\TrainData\img\image_1595.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1595.h5
663 C:\Users\iamte\Downloads\TrainData\img\image_1596.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1596.h5
664 C:\Users\iamte\Downloads\TrainData\img\image_1597.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1597.h5
665 C:\Users\iamte\Downloads\TrainData\img\image_1598.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1598.h5
666 C:\Users\iamte\Downloads\TrainData\img\image_1599.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1599.h5
667 C:\Use

753 C:\Users\iamte\Downloads\TrainData\img\image_1677.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1677.h5
754 C:\Users\iamte\Downloads\TrainData\img\image_1678.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1678.h5
755 C:\Users\iamte\Downloads\TrainData\img\image_1679.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1679.h5
756 C:\Users\iamte\Downloads\TrainData\img\image_168.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_168.h5
757 C:\Users\iamte\Downloads\TrainData\img\image_1680.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1680.h5
758 C:\Users\iamte\Downloads\TrainData\img\image_1681.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1681.h5
759 C:\Users\iamte\Downloads\TrainData\img\image_1682.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1682.h5
760 C:\Users\iamte\Downloads\TrainData\img\image_1683.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1683.h5
761 C:\Users\iamte\Downloads\TrainData\img\image_1684.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1684.h5
762 C:\Users

873 C:\Users\iamte\Downloads\TrainData\img\image_1785.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1785.h5
874 C:\Users\iamte\Downloads\TrainData\img\image_1786.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1786.h5
875 C:\Users\iamte\Downloads\TrainData\img\image_1787.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1787.h5
876 C:\Users\iamte\Downloads\TrainData\img\image_1788.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1788.h5
877 C:\Users\iamte\Downloads\TrainData\img\image_1789.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1789.h5
878 C:\Users\iamte\Downloads\TrainData\img\image_179.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_179.h5
879 C:\Users\iamte\Downloads\TrainData\img\image_1790.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1790.h5
880 C:\Users\iamte\Downloads\TrainData\img\image_1791.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1791.h5
881 C:\Users\iamte\Downloads\TrainData\img\image_1792.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1792.h5
882 C:\Users

956 C:\Users\iamte\Downloads\TrainData\img\image_186.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_186.h5
957 C:\Users\iamte\Downloads\TrainData\img\image_1860.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1860.h5
958 C:\Users\iamte\Downloads\TrainData\img\image_1861.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1861.h5
959 C:\Users\iamte\Downloads\TrainData\img\image_1862.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1862.h5
960 C:\Users\iamte\Downloads\TrainData\img\image_1863.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1863.h5
961 C:\Users\iamte\Downloads\TrainData\img\image_1864.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1864.h5
962 C:\Users\iamte\Downloads\TrainData\img\image_1865.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1865.h5
963 C:\Users\iamte\Downloads\TrainData\img\image_1866.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1866.h5
964 C:\Users\iamte\Downloads\TrainData\img\image_1867.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1867.h5
965 C:\Users

1078 C:\Users\iamte\Downloads\TrainData\img\image_197.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_197.h5
1079 C:\Users\iamte\Downloads\TrainData\img\image_1970.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1970.h5
1080 C:\Users\iamte\Downloads\TrainData\img\image_1971.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1971.h5
1081 C:\Users\iamte\Downloads\TrainData\img\image_1972.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1972.h5
1082 C:\Users\iamte\Downloads\TrainData\img\image_1973.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1973.h5
1083 C:\Users\iamte\Downloads\TrainData\img\image_1974.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1974.h5
1084 C:\Users\iamte\Downloads\TrainData\img\image_1975.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1975.h5
1085 C:\Users\iamte\Downloads\TrainData\img\image_1976.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1976.h5
1086 C:\Users\iamte\Downloads\TrainData\img\image_1977.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_1977.h5
108

1172 C:\Users\iamte\Downloads\TrainData\img\image_2053.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2053.h5
1173 C:\Users\iamte\Downloads\TrainData\img\image_2054.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2054.h5
1174 C:\Users\iamte\Downloads\TrainData\img\image_2055.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2055.h5
1175 C:\Users\iamte\Downloads\TrainData\img\image_2056.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2056.h5
1176 C:\Users\iamte\Downloads\TrainData\img\image_2057.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2057.h5
1177 C:\Users\iamte\Downloads\TrainData\img\image_2058.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2058.h5
1178 C:\Users\iamte\Downloads\TrainData\img\image_2059.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2059.h5
1179 C:\Users\iamte\Downloads\TrainData\img\image_206.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_206.h5
1180 C:\Users\iamte\Downloads\TrainData\img\image_2060.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2060.h5
118

1269 C:\Users\iamte\Downloads\TrainData\img\image_2140.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2140.h5
1270 C:\Users\iamte\Downloads\TrainData\img\image_2141.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2141.h5
1271 C:\Users\iamte\Downloads\TrainData\img\image_2142.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2142.h5
1272 C:\Users\iamte\Downloads\TrainData\img\image_2143.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2143.h5
1273 C:\Users\iamte\Downloads\TrainData\img\image_2144.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2144.h5
1274 C:\Users\iamte\Downloads\TrainData\img\image_2145.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2145.h5
1275 C:\Users\iamte\Downloads\TrainData\img\image_2146.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2146.h5
1276 C:\Users\iamte\Downloads\TrainData\img\image_2147.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2147.h5
1277 C:\Users\iamte\Downloads\TrainData\img\image_2148.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2148.h5
1

1368 C:\Users\iamte\Downloads\TrainData\img\image_223.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_223.h5
1369 C:\Users\iamte\Downloads\TrainData\img\image_2230.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2230.h5
1370 C:\Users\iamte\Downloads\TrainData\img\image_2231.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2231.h5
1371 C:\Users\iamte\Downloads\TrainData\img\image_2232.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2232.h5
1372 C:\Users\iamte\Downloads\TrainData\img\image_2233.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2233.h5
1373 C:\Users\iamte\Downloads\TrainData\img\image_2234.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2234.h5
1374 C:\Users\iamte\Downloads\TrainData\img\image_2235.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2235.h5
1375 C:\Users\iamte\Downloads\TrainData\img\image_2236.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2236.h5
1376 C:\Users\iamte\Downloads\TrainData\img\image_2237.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2237.h5
137

1467 C:\Users\iamte\Downloads\TrainData\img\image_2319.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2319.h5
1468 C:\Users\iamte\Downloads\TrainData\img\image_232.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_232.h5
1469 C:\Users\iamte\Downloads\TrainData\img\image_2320.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2320.h5
1470 C:\Users\iamte\Downloads\TrainData\img\image_2321.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2321.h5
1471 C:\Users\iamte\Downloads\TrainData\img\image_2322.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2322.h5
1472 C:\Users\iamte\Downloads\TrainData\img\image_2323.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2323.h5
1473 C:\Users\iamte\Downloads\TrainData\img\image_2324.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2324.h5
1474 C:\Users\iamte\Downloads\TrainData\img\image_2325.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2325.h5
1475 C:\Users\iamte\Downloads\TrainData\img\image_2326.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2326.h5
147

1557 C:\Users\iamte\Downloads\TrainData\img\image_240.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_240.h5
1558 C:\Users\iamte\Downloads\TrainData\img\image_2400.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2400.h5
1559 C:\Users\iamte\Downloads\TrainData\img\image_2401.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2401.h5
1560 C:\Users\iamte\Downloads\TrainData\img\image_2402.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2402.h5
1561 C:\Users\iamte\Downloads\TrainData\img\image_2403.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2403.h5
1562 C:\Users\iamte\Downloads\TrainData\img\image_2404.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2404.h5
1563 C:\Users\iamte\Downloads\TrainData\img\image_2405.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2405.h5
1564 C:\Users\iamte\Downloads\TrainData\img\image_2406.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2406.h5
1565 C:\Users\iamte\Downloads\TrainData\img\image_2407.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2407.h5
156

1645 C:\Users\iamte\Downloads\TrainData\img\image_248.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_248.h5
1646 C:\Users\iamte\Downloads\TrainData\img\image_2480.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2480.h5
1647 C:\Users\iamte\Downloads\TrainData\img\image_2481.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2481.h5
1648 C:\Users\iamte\Downloads\TrainData\img\image_2482.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2482.h5
1649 C:\Users\iamte\Downloads\TrainData\img\image_2483.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2483.h5
1650 C:\Users\iamte\Downloads\TrainData\img\image_2484.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2484.h5
1651 C:\Users\iamte\Downloads\TrainData\img\image_2485.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2485.h5
1652 C:\Users\iamte\Downloads\TrainData\img\image_2486.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2486.h5
1653 C:\Users\iamte\Downloads\TrainData\img\image_2487.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2487.h5
165

1734 C:\Users\iamte\Downloads\TrainData\img\image_256.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_256.h5
1735 C:\Users\iamte\Downloads\TrainData\img\image_2560.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2560.h5
1736 C:\Users\iamte\Downloads\TrainData\img\image_2561.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2561.h5
1737 C:\Users\iamte\Downloads\TrainData\img\image_2562.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2562.h5
1738 C:\Users\iamte\Downloads\TrainData\img\image_2563.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2563.h5
1739 C:\Users\iamte\Downloads\TrainData\img\image_2564.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2564.h5
1740 C:\Users\iamte\Downloads\TrainData\img\image_2565.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2565.h5
1741 C:\Users\iamte\Downloads\TrainData\img\image_2566.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2566.h5
1742 C:\Users\iamte\Downloads\TrainData\img\image_2567.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2567.h5
174

1817 C:\Users\iamte\Downloads\TrainData\img\image_2634.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2634.h5
1818 C:\Users\iamte\Downloads\TrainData\img\image_2635.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2635.h5
1819 C:\Users\iamte\Downloads\TrainData\img\image_2636.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2636.h5
1820 C:\Users\iamte\Downloads\TrainData\img\image_2637.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2637.h5
1821 C:\Users\iamte\Downloads\TrainData\img\image_2638.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2638.h5
1822 C:\Users\iamte\Downloads\TrainData\img\image_2639.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2639.h5
1823 C:\Users\iamte\Downloads\TrainData\img\image_264.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_264.h5
1824 C:\Users\iamte\Downloads\TrainData\img\image_2640.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2640.h5
1825 C:\Users\iamte\Downloads\TrainData\img\image_2641.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2641.h5
182

1911 C:\Users\iamte\Downloads\TrainData\img\image_2719.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2719.h5
1912 C:\Users\iamte\Downloads\TrainData\img\image_272.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_272.h5
1913 C:\Users\iamte\Downloads\TrainData\img\image_2720.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2720.h5
1914 C:\Users\iamte\Downloads\TrainData\img\image_2721.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2721.h5
1915 C:\Users\iamte\Downloads\TrainData\img\image_2722.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2722.h5
1916 C:\Users\iamte\Downloads\TrainData\img\image_2723.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2723.h5
1917 C:\Users\iamte\Downloads\TrainData\img\image_2724.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2724.h5
1918 C:\Users\iamte\Downloads\TrainData\img\image_2725.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2725.h5
1919 C:\Users\iamte\Downloads\TrainData\img\image_2726.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2726.h5
192

2003 C:\Users\iamte\Downloads\TrainData\img\image_2801.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2801.h5
2004 C:\Users\iamte\Downloads\TrainData\img\image_2802.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2802.h5
2005 C:\Users\iamte\Downloads\TrainData\img\image_2803.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2803.h5
2006 C:\Users\iamte\Downloads\TrainData\img\image_2804.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2804.h5
2007 C:\Users\iamte\Downloads\TrainData\img\image_2805.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2805.h5
2008 C:\Users\iamte\Downloads\TrainData\img\image_2806.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2806.h5
2009 C:\Users\iamte\Downloads\TrainData\img\image_2807.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2807.h5
2010 C:\Users\iamte\Downloads\TrainData\img\image_2808.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2808.h5
2011 C:\Users\iamte\Downloads\TrainData\img\image_2809.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2809.h5
2

2082 C:\Users\iamte\Downloads\TrainData\img\image_2873.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2873.h5
2083 C:\Users\iamte\Downloads\TrainData\img\image_2874.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2874.h5
2084 C:\Users\iamte\Downloads\TrainData\img\image_2875.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2875.h5
2085 C:\Users\iamte\Downloads\TrainData\img\image_2876.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2876.h5
2086 C:\Users\iamte\Downloads\TrainData\img\image_2877.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2877.h5
2087 C:\Users\iamte\Downloads\TrainData\img\image_2878.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2878.h5
2088 C:\Users\iamte\Downloads\TrainData\img\image_2879.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2879.h5
2089 C:\Users\iamte\Downloads\TrainData\img\image_288.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_288.h5
2090 C:\Users\iamte\Downloads\TrainData\img\image_2880.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2880.h5
209

2167 C:\Users\iamte\Downloads\TrainData\img\image_295.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_295.h5
2168 C:\Users\iamte\Downloads\TrainData\img\image_2950.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2950.h5
2169 C:\Users\iamte\Downloads\TrainData\img\image_2951.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2951.h5
2170 C:\Users\iamte\Downloads\TrainData\img\image_2952.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2952.h5
2171 C:\Users\iamte\Downloads\TrainData\img\image_2953.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2953.h5
2172 C:\Users\iamte\Downloads\TrainData\img\image_2954.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2954.h5
2173 C:\Users\iamte\Downloads\TrainData\img\image_2955.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2955.h5
2174 C:\Users\iamte\Downloads\TrainData\img\image_2956.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2956.h5
2175 C:\Users\iamte\Downloads\TrainData\img\image_2957.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_2957.h5
217

2251 C:\Users\iamte\Downloads\TrainData\img\image_3024.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3024.h5
2252 C:\Users\iamte\Downloads\TrainData\img\image_3025.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3025.h5
2253 C:\Users\iamte\Downloads\TrainData\img\image_3026.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3026.h5
2254 C:\Users\iamte\Downloads\TrainData\img\image_3027.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3027.h5
2255 C:\Users\iamte\Downloads\TrainData\img\image_3028.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3028.h5
2256 C:\Users\iamte\Downloads\TrainData\img\image_3029.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3029.h5
2257 C:\Users\iamte\Downloads\TrainData\img\image_303.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_303.h5
2258 C:\Users\iamte\Downloads\TrainData\img\image_3030.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3030.h5
2259 C:\Users\iamte\Downloads\TrainData\img\image_3031.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3031.h5
226

2349 C:\Users\iamte\Downloads\TrainData\img\image_3112.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3112.h5
2350 C:\Users\iamte\Downloads\TrainData\img\image_3113.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3113.h5
2351 C:\Users\iamte\Downloads\TrainData\img\image_3114.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3114.h5
2352 C:\Users\iamte\Downloads\TrainData\img\image_3115.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3115.h5
2353 C:\Users\iamte\Downloads\TrainData\img\image_3116.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3116.h5
2354 C:\Users\iamte\Downloads\TrainData\img\image_3117.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3117.h5
2355 C:\Users\iamte\Downloads\TrainData\img\image_3118.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3118.h5
2356 C:\Users\iamte\Downloads\TrainData\img\image_3119.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3119.h5
2357 C:\Users\iamte\Downloads\TrainData\img\image_312.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_312.h5
235

2442 C:\Users\iamte\Downloads\TrainData\img\image_3197.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3197.h5
2443 C:\Users\iamte\Downloads\TrainData\img\image_3198.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3198.h5
2444 C:\Users\iamte\Downloads\TrainData\img\image_3199.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3199.h5
2445 C:\Users\iamte\Downloads\TrainData\img\image_32.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_32.h5
2446 C:\Users\iamte\Downloads\TrainData\img\image_320.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_320.h5
2447 C:\Users\iamte\Downloads\TrainData\img\image_3200.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3200.h5
2448 C:\Users\iamte\Downloads\TrainData\img\image_3201.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3201.h5
2449 C:\Users\iamte\Downloads\TrainData\img\image_3202.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3202.h5
2450 C:\Users\iamte\Downloads\TrainData\img\image_3203.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3203.h5
2451 C:

2537 C:\Users\iamte\Downloads\TrainData\img\image_3282.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3282.h5
2538 C:\Users\iamte\Downloads\TrainData\img\image_3283.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3283.h5
2539 C:\Users\iamte\Downloads\TrainData\img\image_3284.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3284.h5
2540 C:\Users\iamte\Downloads\TrainData\img\image_3285.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3285.h5
2541 C:\Users\iamte\Downloads\TrainData\img\image_3286.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3286.h5
2542 C:\Users\iamte\Downloads\TrainData\img\image_3287.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3287.h5
2543 C:\Users\iamte\Downloads\TrainData\img\image_3288.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3288.h5
2544 C:\Users\iamte\Downloads\TrainData\img\image_3289.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3289.h5
2545 C:\Users\iamte\Downloads\TrainData\img\image_329.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_329.h5
254

2631 C:\Users\iamte\Downloads\TrainData\img\image_3367.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3367.h5
2632 C:\Users\iamte\Downloads\TrainData\img\image_3368.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3368.h5
2633 C:\Users\iamte\Downloads\TrainData\img\image_3369.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3369.h5
2634 C:\Users\iamte\Downloads\TrainData\img\image_337.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_337.h5
2635 C:\Users\iamte\Downloads\TrainData\img\image_3370.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3370.h5
2636 C:\Users\iamte\Downloads\TrainData\img\image_3371.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3371.h5
2637 C:\Users\iamte\Downloads\TrainData\img\image_3372.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3372.h5
2638 C:\Users\iamte\Downloads\TrainData\img\image_3373.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3373.h5
2639 C:\Users\iamte\Downloads\TrainData\img\image_3374.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3374.h5
264

2735 C:\Users\iamte\Downloads\TrainData\img\image_3460.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3460.h5
2736 C:\Users\iamte\Downloads\TrainData\img\image_3461.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3461.h5
2737 C:\Users\iamte\Downloads\TrainData\img\image_3462.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3462.h5
2738 C:\Users\iamte\Downloads\TrainData\img\image_3463.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3463.h5
2739 C:\Users\iamte\Downloads\TrainData\img\image_3464.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3464.h5
2740 C:\Users\iamte\Downloads\TrainData\img\image_3465.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3465.h5
2741 C:\Users\iamte\Downloads\TrainData\img\image_3466.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3466.h5
2742 C:\Users\iamte\Downloads\TrainData\img\image_3467.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3467.h5
2743 C:\Users\iamte\Downloads\TrainData\img\image_3468.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3468.h5
2

2825 C:\Users\iamte\Downloads\TrainData\img\image_3541.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3541.h5
2826 C:\Users\iamte\Downloads\TrainData\img\image_3542.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3542.h5
2827 C:\Users\iamte\Downloads\TrainData\img\image_3543.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3543.h5
2828 C:\Users\iamte\Downloads\TrainData\img\image_3544.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3544.h5
2829 C:\Users\iamte\Downloads\TrainData\img\image_3545.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3545.h5
2830 C:\Users\iamte\Downloads\TrainData\img\image_3546.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3546.h5
2831 C:\Users\iamte\Downloads\TrainData\img\image_3547.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3547.h5
2832 C:\Users\iamte\Downloads\TrainData\img\image_3548.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3548.h5
2833 C:\Users\iamte\Downloads\TrainData\img\image_3549.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3549.h5
2

2904 C:\Users\iamte\Downloads\TrainData\img\image_3612.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3612.h5
2905 C:\Users\iamte\Downloads\TrainData\img\image_3613.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3613.h5
2906 C:\Users\iamte\Downloads\TrainData\img\image_3614.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3614.h5
2907 C:\Users\iamte\Downloads\TrainData\img\image_3615.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3615.h5
2908 C:\Users\iamte\Downloads\TrainData\img\image_3616.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3616.h5
2909 C:\Users\iamte\Downloads\TrainData\img\image_3617.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3617.h5
2910 C:\Users\iamte\Downloads\TrainData\img\image_3618.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3618.h5
2911 C:\Users\iamte\Downloads\TrainData\img\image_3619.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3619.h5
2912 C:\Users\iamte\Downloads\TrainData\img\image_362.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_362.h5
291

2994 C:\Users\iamte\Downloads\TrainData\img\image_3694.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3694.h5
2995 C:\Users\iamte\Downloads\TrainData\img\image_3695.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3695.h5
2996 C:\Users\iamte\Downloads\TrainData\img\image_3696.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3696.h5
2997 C:\Users\iamte\Downloads\TrainData\img\image_3697.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3697.h5
2998 C:\Users\iamte\Downloads\TrainData\img\image_3698.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3698.h5
2999 C:\Users\iamte\Downloads\TrainData\img\image_3699.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3699.h5
3000 C:\Users\iamte\Downloads\TrainData\img\image_37.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_37.h5
3001 C:\Users\iamte\Downloads\TrainData\img\image_370.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_370.h5
3002 C:\Users\iamte\Downloads\TrainData\img\image_3700.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3700.h5
3003 C:

3082 C:\Users\iamte\Downloads\TrainData\img\image_3773.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3773.h5
3083 C:\Users\iamte\Downloads\TrainData\img\image_3774.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3774.h5
3084 C:\Users\iamte\Downloads\TrainData\img\image_3775.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3775.h5
3085 C:\Users\iamte\Downloads\TrainData\img\image_3776.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3776.h5
3086 C:\Users\iamte\Downloads\TrainData\img\image_3777.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3777.h5
3087 C:\Users\iamte\Downloads\TrainData\img\image_3778.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3778.h5
3088 C:\Users\iamte\Downloads\TrainData\img\image_3779.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3779.h5
3089 C:\Users\iamte\Downloads\TrainData\img\image_378.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_378.h5
3090 C:\Users\iamte\Downloads\TrainData\img\image_3780.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_3780.h5
309

3184 C:\Users\iamte\Downloads\TrainData\img\image_445.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_445.h5
3185 C:\Users\iamte\Downloads\TrainData\img\image_446.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_446.h5
3186 C:\Users\iamte\Downloads\TrainData\img\image_447.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_447.h5
3187 C:\Users\iamte\Downloads\TrainData\img\image_448.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_448.h5
3188 C:\Users\iamte\Downloads\TrainData\img\image_449.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_449.h5
3189 C:\Users\iamte\Downloads\TrainData\img\image_45.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_45.h5
3190 C:\Users\iamte\Downloads\TrainData\img\image_450.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_450.h5
3191 C:\Users\iamte\Downloads\TrainData\img\image_451.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_451.h5
3192 C:\Users\iamte\Downloads\TrainData\img\image_452.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_452.h5
3193 C:\Users\iamte\D

3284 C:\Users\iamte\Downloads\TrainData\img\image_535.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_535.h5
3285 C:\Users\iamte\Downloads\TrainData\img\image_536.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_536.h5
3286 C:\Users\iamte\Downloads\TrainData\img\image_537.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_537.h5
3287 C:\Users\iamte\Downloads\TrainData\img\image_538.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_538.h5
3288 C:\Users\iamte\Downloads\TrainData\img\image_539.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_539.h5
3289 C:\Users\iamte\Downloads\TrainData\img\image_54.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_54.h5
3290 C:\Users\iamte\Downloads\TrainData\img\image_540.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_540.h5
3291 C:\Users\iamte\Downloads\TrainData\img\image_541.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_541.h5
3292 C:\Users\iamte\Downloads\TrainData\img\image_542.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_542.h5
3293 C:\Users\iamte\D

3361 C:\Users\iamte\Downloads\TrainData\img\image_604.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_604.h5
3362 C:\Users\iamte\Downloads\TrainData\img\image_605.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_605.h5
3363 C:\Users\iamte\Downloads\TrainData\img\image_606.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_606.h5
3364 C:\Users\iamte\Downloads\TrainData\img\image_607.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_607.h5
3365 C:\Users\iamte\Downloads\TrainData\img\image_608.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_608.h5
3366 C:\Users\iamte\Downloads\TrainData\img\image_609.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_609.h5
3367 C:\Users\iamte\Downloads\TrainData\img\image_61.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_61.h5
3368 C:\Users\iamte\Downloads\TrainData\img\image_610.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_610.h5
3369 C:\Users\iamte\Downloads\TrainData\img\image_611.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_611.h5
3370 C:\Users\iamte\D

3444 C:\Users\iamte\Downloads\TrainData\img\image_68.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_68.h5
3445 C:\Users\iamte\Downloads\TrainData\img\image_680.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_680.h5
3446 C:\Users\iamte\Downloads\TrainData\img\image_681.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_681.h5
3447 C:\Users\iamte\Downloads\TrainData\img\image_682.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_682.h5
3448 C:\Users\iamte\Downloads\TrainData\img\image_683.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_683.h5
3449 C:\Users\iamte\Downloads\TrainData\img\image_684.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_684.h5
3450 C:\Users\iamte\Downloads\TrainData\img\image_685.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_685.h5
3451 C:\Users\iamte\Downloads\TrainData\img\image_686.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_686.h5
3452 C:\Users\iamte\Downloads\TrainData\img\image_687.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_687.h5
3453 C:\Users\iamte\D

3527 C:\Users\iamte\Downloads\TrainData\img\image_754.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_754.h5
3528 C:\Users\iamte\Downloads\TrainData\img\image_755.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_755.h5
3529 C:\Users\iamte\Downloads\TrainData\img\image_756.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_756.h5
3530 C:\Users\iamte\Downloads\TrainData\img\image_757.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_757.h5
3531 C:\Users\iamte\Downloads\TrainData\img\image_758.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_758.h5
3532 C:\Users\iamte\Downloads\TrainData\img\image_759.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_759.h5
3533 C:\Users\iamte\Downloads\TrainData\img\image_76.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_76.h5
3534 C:\Users\iamte\Downloads\TrainData\img\image_760.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_760.h5
3535 C:\Users\iamte\Downloads\TrainData\img\image_761.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_761.h5
3536 C:\Users\iamte\D

3610 C:\Users\iamte\Downloads\TrainData\img\image_829.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_829.h5
3611 C:\Users\iamte\Downloads\TrainData\img\image_83.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_83.h5
3612 C:\Users\iamte\Downloads\TrainData\img\image_830.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_830.h5
3613 C:\Users\iamte\Downloads\TrainData\img\image_831.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_831.h5
3614 C:\Users\iamte\Downloads\TrainData\img\image_832.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_832.h5
3615 C:\Users\iamte\Downloads\TrainData\img\image_833.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_833.h5
3616 C:\Users\iamte\Downloads\TrainData\img\image_834.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_834.h5
3617 C:\Users\iamte\Downloads\TrainData\img\image_835.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_835.h5
3618 C:\Users\iamte\Downloads\TrainData\img\image_836.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_836.h5
3619 C:\Users\iamte\D

3695 C:\Users\iamte\Downloads\TrainData\img\image_905.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_905.h5
3696 C:\Users\iamte\Downloads\TrainData\img\image_906.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_906.h5
3697 C:\Users\iamte\Downloads\TrainData\img\image_907.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_907.h5
3698 C:\Users\iamte\Downloads\TrainData\img\image_908.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_908.h5
3699 C:\Users\iamte\Downloads\TrainData\img\image_909.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_909.h5
3700 C:\Users\iamte\Downloads\TrainData\img\image_91.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_91.h5
3701 C:\Users\iamte\Downloads\TrainData\img\image_910.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_910.h5
3702 C:\Users\iamte\Downloads\TrainData\img\image_911.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_911.h5
3703 C:\Users\iamte\Downloads\TrainData\img\image_912.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_912.h5
3704 C:\Users\iamte\D

3781 C:\Users\iamte\Downloads\TrainData\img\image_983.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_983.h5
3782 C:\Users\iamte\Downloads\TrainData\img\image_984.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_984.h5
3783 C:\Users\iamte\Downloads\TrainData\img\image_985.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_985.h5
3784 C:\Users\iamte\Downloads\TrainData\img\image_986.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_986.h5
3785 C:\Users\iamte\Downloads\TrainData\img\image_987.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_987.h5
3786 C:\Users\iamte\Downloads\TrainData\img\image_988.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_988.h5
3787 C:\Users\iamte\Downloads\TrainData\img\image_989.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_989.h5
3788 C:\Users\iamte\Downloads\TrainData\img\image_99.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_99.h5
3789 C:\Users\iamte\Downloads\TrainData\img\image_990.h5 C:\Users\iamte\Downloads\TrainData\mask\mask_990.h5
3790 C:\Users\iamte\D

In [164]:
with open('TRAIN_XX.npy', 'wb') as f:
    np.save(f, TRAIN_XX)

with open('TRAIN_YY.npy', 'wb') as f:
    np.save(f, TRAIN_YY)   

In [ ]:
import random

random.Random(42).shuffle(TRAIN_XX)
random.Random(42).shuffle(TRAIN_YY)

In [165]:
from Unet import UNet
from .metrics import recall_m, precision_m, f1_m

model = Unet(128, 128, 5, 3, 3, problem_type="Classification")
model.compile(optimizer='adam', loss='binary_crossentropy', metrics = [recall_m, precision_m, f1_m])

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
from keras.callbacks import ModelCheckpoint

checkpoint = ModelCheckpoint("best_model.hdf5", monitor='f1_m', verbose=1, save_best_only=True, mode='auto', period=1) 

history = model.fit(train_gen, 
          epochs=epochs, 
          validation_data=test_gen,
          verbose = 1)

# Rough

In [154]:
f_data = np.zeros((1, 128,128, 3))
with h5py.File(path_single) as hdf:
    ls = list(hdf.keys())
    data = np.array(hdf.get('img'))
    print(data.shape)
    
    data_red = data[:, :, 3]
    data_green = data[:, :, 2]
    data_blue = data[:, :, 1]
    data_nir = data[:, :, 7]
    data_rgb = data[:, :, 3:0:-1]
#     print(data[:, :, 12])
    data_ndvi = np.divide(data_nir - data_red,np.add(data_nir, data_red))
    print(data_ndvi.shape, "data_ndvi")
    print(data_ndvi.shape)
    f_data[0, :, :, 0] =data_ndvi
    f_data[0, :, :, 1] = data[:, :, 12]
    f_data[0, :, :, 2] = data[:, :, 13]

    print(data_ndvi.shape, f_data.shape, f_data)
    

(128, 128, 14)
(128, 128) data_ndvi
(128, 128)
(128, 128) (1, 128, 128, 3) [[[[ 0.00394924  1.33055509  2.12853657]
   [-0.06908581  1.23199545  2.13112446]
   [-0.02598334  1.23199545  2.13112446]
   ...
   [ 0.02175226  1.03487618  1.89045102]
   [ 0.0137045   1.23199545  1.89433285]
   [ 0.03552094  1.37983491  1.90080257]]

  [[ 0.08882324  1.23199545  2.13630023]
   [ 0.01556584  1.13343582  2.13759417]
   [-0.04380046  1.13343582  2.13759417]
   ...
   [ 0.08107639  0.83775691  1.88268736]
   [ 0.03013263  1.13343582  1.88786313]
   [-0.08405606  1.626234    1.89562679]]

  [[ 0.07065672  1.23199545  2.14276995]
   [ 0.04859406  1.18271564  2.14406389]
   [ 0.01584496  1.18271564  2.14406389]
   ...
   [ 0.09344456  0.98559636  1.88009948]
   [ 0.02542377  1.28127527  1.88786313]
   [-0.12293254  1.57695418  1.89692074]]

  ...

  [[ 0.15182325  1.084156    1.91762383]
   [ 0.15425885  0.98559636  1.91762383]
   [ 0.13063619  0.83775691  1.91762383]
   ...
   [ 0.08517528  1.7247

In [156]:
f_mask = np.zeros((2, 128, 128))
with h5py.File(path_single_mask) as hdf:
    ls = list(hdf.keys())
    print(ls)
    data=np.array(hdf.get('mask'))
    f_mask[0, :, :] = data
    f_mask[1, :, :] = data
    print(f_mask)

['mask']
[[[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
